# Generated by Django 4.2.7 on 2024-01-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredientamount_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientamount_set', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
